package View;

import Controller.BarangDAO;
import Controller.PegawaiDAO;
import Model.Barang;
import Model.Pegawai;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ditya Geraldy
 */
public class formTransaksi extends javax.swing.JFrame 
{

    boolean bolInsert = false;
    boolean bolDelete = false;
    boolean bolFinish = false;

    /**
     * Creates new form formTransaksi
     */
    public formTransaksi() 
    {
        initComponents();
        readData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Vx Hardware");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Form Barang");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Harga", "Jumlah", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kode Barang          :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Jumlah                   :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Total Harga     (Rp) :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Dibayar           (Rp) :");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Kembalian        (Rp) :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Kode Pegawai :");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Finish");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setEnabled(false);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setText("0");
        jTextField2.setEnabled(false);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setText("0");
        jTextField3.setEnabled(false);
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.setText("0");
        jTextField4.setEnabled(false);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBox2.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(28, 28, 28)
                                .addComponent(jButton2)
                                .addGap(26, 26, 26)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4)
                                    .addComponent(jComboBox2, 0, 245, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (bolInsert != true) 
        {
            inputTextFromTable(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: FINISH 
        if(bolFinish == false)
        {
            readData();
            jTextField3.setEnabled(true);
            jButton1.setVisible(false);
            jButton2.setVisible(false);
            jButton3.setText("PRINT");
            bolFinish = true;
        }
        else if(bolFinish == true)
        {
            if(Integer.parseInt(jTextField4.getText())< 0)
            {
                JOptionPane.showMessageDialog(rootPane, "Cek kembali pembayaran");
            }
            else
            {
                printStruk();
                clearTable();
                readData();
                jTextField3.setEnabled(false);
                jButton1.setVisible(true);
                jButton2.setVisible(true);
                jButton3.setText("Finish");
                bolFinish = false;
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: INSERT
        if(bolInsert == false)
        {
            readData();
            jComboBox2.setEnabled(true);
            jTextField1.setEnabled(true);
            jButton1.setText("ADD");
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            bolInsert = true;
        }
        else if(bolInsert == true)
        {
            insertData(jComboBox2.getSelectedItem().toString(), jTextField1.getText());
            readData();
            jComboBox2.setEnabled(false);
            jTextField1.setEnabled(false);
            jButton1.setText("Insert");
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            bolInsert = false;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: DELETE
        if(bolDelete == false)
        {
            readData();
            //jComboBox2.setEnabled(true);
            jButton1.setVisible(false);
            jButton2.setText("REMOVE");
            jButton3.setVisible(false);
            bolDelete = true;
        }
        else if(bolDelete == true)
        {
            deleteData();
            readData();
            //jComboBox2.setEnabled(false);
            jButton1.setVisible(true);
            jButton2.setText("Delete");
            jButton3.setVisible(true);
            bolDelete = false;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
        int total = Integer.parseInt(jTextField2.getText());
        int bayar = Integer.parseInt(jTextField3.getText());
        jTextField4.setText(String.valueOf(bayar-total));
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        // TODO add your handling code here:
        jTextField3.setText("");
    }//GEN-LAST:event_jTextField3MouseClicked

    void readData() 
    {
        jComboBox1.removeAllItems();
        List<Pegawai> pegawai = new PegawaiDAO().getPegawai();
        String[][] dataPegawai = new String[pegawai.size()][5];
        int indexPegawai = 0;
        for (Pegawai m : pegawai) 
        {
            dataPegawai[indexPegawai][0] = m.getKodePegawai().toString();
            jComboBox1.addItem(dataPegawai[indexPegawai][0]);
            ++indexPegawai;
        }
        
        jComboBox2.removeAllItems();
        List<Barang> barang = new BarangDAO().getBarang();
        String[][] dataBarang = new String[barang.size()][5];
        int indexBarang = 0;
        for (Barang m : barang) 
        {
            dataBarang[indexBarang][0] = m.getKodeBarang().toString();
            jComboBox2.addItem(dataBarang[indexBarang][0]);
            ++indexBarang;
        }
        jTextField1.setText("");
        jTextField3.setText("0");
        
        //total transaksi
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int totalTr = 0;
        int rowCount = model.getRowCount();

        for (int i = 0; i < rowCount; i++) 
        {
            totalTr += Integer.parseInt(model.getValueAt(i, 4).toString());
            jTextField2.setText(Integer.toString(totalTr));
            jTextField4.setText(Integer.toString(0 - 
                    (Integer.parseInt(jTextField2.getText()))));
        }
    }

    void insertData(String kodeBarang, String jumlahBarang) 
    {
        Barang barangs = new BarangDAO().getBarangByKode(kodeBarang);
        String data1 = kodeBarang;
        String data2 = barangs.getNamaBarang();
        String data3 = String.valueOf(barangs.getHargaBarang());
        String data4 = jumlahBarang;
        String data5 = Integer.toString((Integer.parseInt(data3)) * (Integer.parseInt(data4)));
        Object[] row = {data1, data2, data3, data4, data5};
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(row);

        //update stok
        new BarangDAO().deleteBarang(Long.parseLong(data1));
        Barang m = new Barang();
        m.setKodeBarang(Long.parseLong(data1));
        m.setNamaBarang(data2);
        m.setHargaBarang(Long.parseLong(data3));
        m.setStokBarang(barangs.getStokBarang() - Long.parseLong(data4));
        new BarangDAO().updateBarang(m);
    }

    void deleteData() 
    {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.removeRow(jTable1.getSelectedRow());

        //update stok
        String kodeBarang = jComboBox2.getSelectedItem().toString();
        Barang barangs = new BarangDAO().getBarangByKode(kodeBarang);
        Barang m = new BarangDAO().getBarangByKode(kodeBarang);
        m.setStokBarang(barangs.getStokBarang()
                + Long.parseLong(jTextField1.getText()));
        new BarangDAO().updateBarang(m);

    }

    void inputTextFromTable(int rowIndex)
    {
        Object selectedObjectKode = (Object) jTable1.getModel().getValueAt(rowIndex, 0);
        Object selectedObjectJumlah = (Object) jTable1.getModel().getValueAt(rowIndex, 3);        
        jComboBox2.setSelectedItem(selectedObjectKode);
        jTextField1.setText(selectedObjectJumlah.toString()); 
    }
    
    void printStruk()
    {
        try 
        {
            Pegawai pgw = new PegawaiDAO().getPegawaiByKode(jComboBox1.
                    getSelectedItem().toString());
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int rowCount = model.getRowCount();
            File fileStruk = new File("E:/struk.txt");
            FileOutputStream fosStruk = new FileOutputStream(fileStruk);
            OutputStreamWriter oswStruk = new OutputStreamWriter(fosStruk);
            Writer wr = new BufferedWriter(oswStruk);
            wr.write("-----------------------------------------------------------------------------\n");
            wr.write("Vx Hardware\n");
            wr.write("-----------------------------------------------------------------------------\n");
            wr.write("No\t\t\tNama\t\t\tHarga\t\t\tJumlah\t\t\tTotal\n");
            wr.write("-----------------------------------------------------------------------------\n");
            for (int i = 0; i < rowCount; i++) 
            {
                wr.write((i + 1) + "\t");
                wr.write(model.getValueAt(i, 1).toString() + "\t\t\t");
                wr.write(model.getValueAt(i, 2).toString() + "\t\t\t");
                wr.write(model.getValueAt(i, 3).toString() + "\t\t\t");
                wr.write(model.getValueAt(i, 4).toString() + "\n");
            }
            wr.write("-----------------------------------------------------------------------------\n");
            wr.write("Total Transaksi (Rp) = " + jTextField2.getText() + "\n");
            wr.write("Bayar (Rp) = " + jTextField3.getText() + "\n");
            wr.write("Kembalian (Rp) = " + jTextField4.getText() + "\n");
            wr.write("-----------------------------------------------------------------------------\n");
            wr.write("Kasir = " + pgw.getNamaPegawai() + "\n");
            wr.write("Terima kasih atas kunjungan anda, selamat berbelanja kembali\n");
            wr.write("-----------------------------------------------------------------------------\n");
            wr.close();
        } 
        catch (IOException e) 
        {
            System.err.println("Problem writing to the file");
        }
    }
    
    void clearTable()
    {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < model.getRowCount(); i++) 
        {
            model.removeRow(i);
        }
        if (model.getRowCount() > 0) 
        {
            model.removeRow(model.getRowCount() - 1);
        }
        jTextField2.setText("0");
        jTextField4.setText("0");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run()
            {
                new formTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
